<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.1.0" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.1.0.4" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" Version="2.0.0-rc3.3" />
        <PackageReference Include="ReactiveUI" Version="20.1.63" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\DashboardView.axaml.cs">
        <DependentUpon>DashboardView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\CustomTitleBar.axaml.cs">
        <DependentUpon>CustomTitleBar.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\SampleNumberInput.axaml.cs">
        <DependentUpon>SampleNumberInput.axaml</DependentUpon>
      </Compile>
      <Compile Update="Views\MiniViews\SampleNumberInput.axaml.cs">
        <DependentUpon>SampleNumberInput.axaml</DependentUpon>
        <SubType>Code</SubType>
      <Compile Update="Views\SampleNumberInput.axaml.cs">
        <DependentUpon>SampleNumberInput.axaml</DependentUpon>
      </Compile>
    </ItemGroup>
</Project>
